# Generated by Django 4.1.1 on 2022-09-30 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Social', '0004_alter_dislike_article_alter_like_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='like',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='DisLike',
        ),
    ]
